table Qualifying
	lineageTag: 919c1a9c-57b9-4b59-b6b8-433b1d6604db

	column Season
		dataType: int64
		formatString: 0
		lineageTag: ff698f56-beb6-4e3c-8306-2ee8eab36f22
		summarizeBy: sum
		sourceColumn: Season

		annotation SummarizationSetBy = Automatic

	column Round
		dataType: int64
		formatString: 0
		lineageTag: 97a6b8b4-1a21-4f74-8560-cb81d45c6bc3
		summarizeBy: none
		sourceColumn: Round

		annotation SummarizationSetBy = Automatic

	column QualiPosition
		dataType: int64
		formatString: 0
		lineageTag: 91616bf8-1e71-498b-8872-9cb691bf1688
		summarizeBy: sum
		sourceColumn: QualiPosition

		annotation SummarizationSetBy = Automatic

	column DriverId
		dataType: string
		lineageTag: 7c052791-b6ba-411c-92fd-352de92dcaa5
		summarizeBy: none
		sourceColumn: DriverId

		annotation SummarizationSetBy = Automatic

	column ConstructorId
		dataType: string
		lineageTag: 2deddeec-866c-49b0-9b16-45c9b7ad6017
		summarizeBy: none
		sourceColumn: ConstructorId

		annotation SummarizationSetBy = Automatic

	column Q1
		dataType: string
		lineageTag: 368e2c3b-1e29-4fec-972f-5fe1d87b3e54
		summarizeBy: none
		sourceColumn: Q1

		annotation SummarizationSetBy = Automatic

	column Q2
		dataType: string
		lineageTag: 46368d7b-932b-4426-a927-4a575ee21a4b
		summarizeBy: none
		sourceColumn: Q2

		annotation SummarizationSetBy = Automatic

	column Q3
		dataType: string
		lineageTag: 696110b1-5081-4aad-9846-75e0e592d678
		summarizeBy: none
		sourceColumn: Q3

		annotation SummarizationSetBy = Automatic

	partition Qualifying = m
		mode: import
		source =
				// Query: Qualifying
				// Purpose: Qualifying results — one row per driver per qualifying session.
				// Source: Jolpica Ergast mirror — /2026/qualifying.json
				// Notes:
				//   - Q1, Q2, Q3 are time strings ("1:23.456") or null if driver didn't reach that segment
				//   - Drivers eliminated in Q1 will have Q2 and Q3 null
				//   - For grid-penalty-adjusted analysis, join to Results[Grid] not QualiPosition
				
				let
				    Source = Json.Document(Web.Contents("https://api.jolpi.ca/ergast/f1/2026/qualifying.json?limit=1000")),
				    Races = Source[MRData][RaceTable][Races],
				    ToTable = Table.FromList(Races, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    ExpandRace = Table.ExpandRecordColumn(ToTable, "Column1",
				        {"season", "round", "QualifyingResults"},
				        {"Season", "Round", "QualifyingResults"}),
				    ExpandQ = Table.ExpandListColumn(ExpandRace, "QualifyingResults"),
				    ExpandQRecord = Table.ExpandRecordColumn(ExpandQ, "QualifyingResults",
				        {"position", "Driver", "Constructor", "Q1", "Q2", "Q3"},
				        {"QualiPosition", "Driver", "Constructor", "Q1", "Q2", "Q3"}),
				    ExpandDriver = Table.ExpandRecordColumn(ExpandQRecord, "Driver",
				        {"driverId"},
				        {"DriverId"}),
				    ExpandConstructor = Table.ExpandRecordColumn(ExpandDriver, "Constructor",
				        {"constructorId"},
				        {"ConstructorId"}),
				    Typed = Table.TransformColumnTypes(ExpandConstructor, {
				        {"Season", Int64.Type},
				        {"Round", Int64.Type},
				        {"QualiPosition", Int64.Type}
				    })
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

